spring:
  application:
    name: CommunityService

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

  data:
    redis:
      database: 0
      host: ${HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60000

rabbitmq:
  exchange:
    notification: ${NOTIFICATION_EXCHANGE}
  routingKey:
    comment: ${COMMENT_ROUTING_KEY}
    reaction: ${REACTION_ROUTING_KEY}
    post: ${POST_ROUTING_KEY}

firebase:
  projectId: ${FIREBASE_PROJECT_ID}
  storage:
    bucket: ${FIREBASE_STORAGE_BUCKET}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

server:
  port: ${PORT}