spring:
  application:
    name: AnalyticService

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    exchange:
      notification: ${NOTIFICATION_EXCHANGE}
      event: ${EVENT_EXCHANGE}
    routingKey:
      notification: ${NOTIFICATION_ROUTING_KEY}
      event: ${EVENT_ROUTING_KEY}

  data:
    redis:
      database: 0
      host: ${HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60000

rabbitmq:
  exchange:
    notification: ${NOTIFICATION_EXCHANGE}
  routingKey:
    comment: ${COMMENT_ROUTING_KEY}
    reaction: ${REACTION_ROUTING_KEY}
    post: ${POST_ROUTING_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

server:
  port: ${PORT}