spring:
  application:
    name: AuthorizationServer
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      authorizationserver:
        issuer-uri: http://${HOST}:${PORT}
      client:
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}
        redirect-uri: ${REDIRECT_URI}
      key:
        public-key: classpath:public.pem
        private-key: classpath:private.pem

  datasource:
    url: jdbc:postgresql://${HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT}