spring:
  application:
    name: AggregationService
  config:
    import: optional:file:.env[.properties]

server:
  port: ${PORT}

feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    com.volunteerhub.AggregationService.client: DEBUG


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}